Pages/Almacenista/AgregarMaterial.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ProyectoAlmacen.Models;
using static ProyectoAlmacen.Pages.Almacenista.OpcionesMaterialesModel;

namespace ProyectoAlmacen.Pages.Almacenista
{
    public class AgregarMaterialModel : PageModel
    {
        private readonly TuDbContext _dbContext;
        [BindProperty]
        public Materiale materialAgregar { get; set; }
        [BindProperty]
        public DatosMateriale datoMaterialAgregar { get; set; }
        public bool EsNuevo { get; set; } = true;

        public AgregarMaterialModel(TuDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public List<DatosMateriale> NombresExistentes { get; set; }

        public IActionResult OnGet(long id)
        {
            /*if (HttpContext.Session.GetString("TipoUsuario") != "Almacenista")
            {
                Response.Redirect("/Error");
            }*/
            datoMaterialAgregar = new DatosMateriale();
            materialAgregar = new Materiale();

            var materialRecuperado = _dbContext.Materiales.Include(m => m.DatosMaterialesNavigation).FirstOrDefault(m => m.NumeroInventario == id.ToString());
            if (materialRecuperado != null)
            {
                datoMaterialAgregar.Id = long.Parse(materialRecuperado.NumeroInventario); // Asigna el Id existente si lo tienes
                datoMaterialAgregar.Nombre = materialRecuperado.DatosMaterialesNavigation?.Nombre;
                datoMaterialAgregar.Descripcion = materialRecuperado.DatosMaterialesNavigation?.Descripcion;
                materialAgregar.NumeroInventario = materialRecuperado.NumeroInventario;
                materialAgregar.AnioMaterial = materialRecuperado.AnioMaterial; // Asumiendo que hay una propiedad Anio en tu modelo
                materialAgregar.Estado = materialRecuperado.Estado;
                EsNuevo = false;
            }

            NombresExistentes = _dbContext.DatosMateriales.ToList();
            return Page();
        }

        public IActionResult OnPost()
        {
            EsNuevo = _dbContext.Materiales.Any(m => m.NumeroInventario == materialAgregar.NumeroInventario);
            if (!EsNuevo)
            {
                var nuevoMaterial = new Materiale();
                if (datoMaterialAgregar.Id == -1)
                {
                    var nuevoDatoMaterial = new DatosMateriale
                    {
                        Nombre = datoMaterialAgregar.Nombre,
                        Descripcion = datoMaterialAgregar.Descripcion,
                    };

                    _dbContext.DatosMateriales.Add(nuevoDatoMaterial);
                    _dbContext.SaveChanges();

                    Console.WriteLine("Nuevo dato material: " + nuevoDatoMaterial.Id);
                    materialAgregar.DatosMateriales = nuevoDatoMaterial.Id;

                    // Crear un nuevo Materiale y asignarle los valores
                    nuevoMaterial = new Materiale
                    {
                        NumeroInventario = materialAgregar.NumeroInventario,
                        DatosMateriales = materialAgregar.DatosMateriales,
                        AnioMaterial = materialAgregar.AnioMaterial,
                        Estado = materialAgregar.Estado,
                    };
                }
                else
                {
                    nuevoMaterial = new Materiale
                    {
                        NumeroInventario = materialAgregar.NumeroInventario,
                        DatosMateriales = datoMaterialAgregar.Id,
                        AnioMaterial = materialAgregar.AnioMaterial,
                        Estado = materialAgregar.Estado,
                    };
                }



                // Agregar el nuevo Materiale a la base de datos
                _dbContext.Materiales.Add(nuevoMaterial);
                _dbContext.SaveChanges();
            }
            else
            {
                var materialRecuperado = _dbContext.Materiales.FirstOrDefault(m => m.NumeroInventario == materialAgregar.NumeroInventario);
                if (materialRecuperado != null)
                {
                    Console.WriteLine("Material recuperado: " + materialRecuperado.NumeroInventario);
                    materialRecuperado.AnioMaterial = materialAgregar.AnioMaterial; // Asumiendo que hay una propiedad Anio en tu modelo
                    materialRecuperado.Estado = materialAgregar.Estado;

                    _dbContext.SaveChanges();
                }


            }


            // Redirige a la página de lista de materiales después de agregar
            return RedirectToPage("/Almacenista/OpcionesMateriales");
        }
    }
}

Pages/Almacenista/OpcionesMateriales.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ProyectoAlmacen.Models;
using System.Collections.Generic;

namespace ProyectoAlmacen.Pages.Almacenista
{
    public class OpcionesMaterialesModel : PageModel
    {
        private readonly TuDbContext _dbContext;
        public OpcionesMaterialesModel(TuDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public List<Materiale> Materiales { get; set; } = new List<Materiale>();
        public Materiale Material { get; set; } = new Materiale();

        public void OnGet()
        {
            if (HttpContext.Session.GetString("TipoUsuario") != "Almacenista")
            {
                Response.Redirect("/Error");
            }

            Materiales = _dbContext.Materiales.Include(m => m.DatosMaterialesNavigation).ToList();
        }

        public IActionResult OnPostEditarMaterial(long materialId){
            return RedirectToPage("/Almacenista/AgregarMaterial", new { id = materialId});
        }

        public IActionResult OnPostEliminarMaterial(string materialId){
            Console.WriteLine("MaterialId: " + materialId);
            var material = _dbContext.Materiales.FirstOrDefault(m => m.NumeroInventario == materialId);
            _dbContext.Materiales.Remove(material);
            _dbContext.SaveChanges();
            return RedirectToPage("/Almacenista/OpcionesMateriales");
        }
    }
}

Pages/Almacenista/SolicitudesAlmacen.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ProyectoAlmacen.Models;
using ProyectoAlmacen.Pages.Profesor;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoAlmacen.Pages.Almacenista
{
    public class SolicitudesAlmacenModel : PageModel
    {
        private readonly TuDbContext _dbContext;

        public SolicitudesAlmacenModel(TuDbContext context)
        {
            _dbContext = context;
        }

        public List<Solicitude> SolicitudesConMateriales { get; set; } = new List<Solicitude>();
        public List<Solicitude> SolicitudesAtrasadas { get; set; } = new List<Solicitude>();
        public List<Prestamo> Prestamos { get; set; } = new List<Prestamo>();   
        public Prestamo prestamo { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            if (HttpContext.Session.GetString("TipoUsuario") != "Almacenista")
            {
                Console.WriteLine("Error: /Almacenista/SolicitudesAlmacen error en tipo de usuario");
                Response.Redirect("/Error");
            }

            SolicitudesConMateriales =_dbContext.Solicitudes
                                        .Include(m => m.MaterialSolicituds)
                                            .ThenInclude(m => m.NumeroInventarioNavigation)
                                                .ThenInclude(m => m.DatosMaterialesNavigation)
                                        .Include(m => m.LaboratorioNavigation)
                                        .Include(m => m.IdusuarioNavigation)
                                        .Include(m => m.ProfesorNavigation)
                                            .ThenInclude(p => p.IdusuarioNavigation)
                                        .Where(s => s.EstadoSolicitud == "Aprobada")
                                        .AsEnumerable()
                                        .Where(s => DateTime.Parse(s.FechaSolicitud) >= DateTime.Today)
                                        .OrderBy(s => s.FechaSolicitud)
                                        .ToList();

            SolicitudesAtrasadas = _dbContext.Solicitudes
                                        .Include(m => m.MaterialSolicituds)
                                            .ThenInclude(m => m.NumeroInventarioNavigation)
                                                .ThenInclude(m => m.DatosMaterialesNavigation)
                                        .Include(m => m.LaboratorioNavigation)
                                        .Include(m => m.IdusuarioNavigation)
                                        .Include(m => m.ProfesorNavigation)
                                            .ThenInclude(p => p.IdusuarioNavigation)
                                        .Where(s => s.EstadoSolicitud == "Prestado")
                                        .AsEnumerable()
                                        .Where(s => DateTime.Parse(s.FechaSolicitud) < DateTime.Today ||
                                        (DateTime.Parse(s.FechaSolicitud) == DateTime.Today &&
                                        TimeSpan.Parse(s.HoraRetorno) < (DateTime.Now.TimeOfDay - TimeSpan.FromMinutes(15))))
                                        .OrderBy(s => s.FechaSolicitud)
                                        .ToList();

            Prestamos = _dbContext.Prestamos.Include(p => p.IdsolicitudNavigation.MaterialSolicituds)
                                                    .ThenInclude(m => m.NumeroInventarioNavigation)
                                                        .ThenInclude(m => m.DatosMaterialesNavigation)
                                            .Include(m => m.IdsolicitudNavigation.LaboratorioNavigation)
                                            .Include(m => m.IdsolicitudNavigation.IdusuarioNavigation)
                                            .Include(m => m.IdsolicitudNavigation.ProfesorNavigation)
                                                .ThenInclude(p => p.IdusuarioNavigation)
                                            .Where(s => s.FechaDevolucion == null)                                                 
                                            .ToList();

            return Page();
        }

        public IActionResult OnPostPrestar(long solicitudId)
        {
            CambiarEstadoSolicitud(solicitudId, "Prestado");
            GenerarPrestamo(solicitudId);
            return RedirectToPage();
        }
        private void CambiarEstadoSolicitud(long solicitudId, string nuevoEstado)
        {
            var solicitud = _dbContext.Solicitudes.Find(solicitudId);

            if (solicitud != null)
            {
                solicitud.EstadoSolicitud = nuevoEstado;
                _dbContext.SaveChanges();
            }
        }

        private void GenerarPrestamo(long solicitudId)
        {
            // Obtener la solicitud correspondiente
            var solicitud = _dbContext.Solicitudes.Find(solicitudId);

            if (solicitud != null)
            {
                // Crear un nuevo objeto Prestamo
                var prestamo = new Prestamo
                {
                    Idsolicitud = solicitudId,
                    FechaDevolucion = null,
                    EstadoPrestamo = "Pendiente"
                };

                // Agregar el prestamo a la tabla Prestamos
                _dbContext.Prestamos.Add(prestamo);

                // Guardar los cambios en la base de datos
                _dbContext.SaveChanges();
            }
        }

    }
}

Pages/Almacenista/AgregarMaterial.cshtml
@page
@model ProyectoAlmacen.Pages.Almacenista.AgregarMaterialModel

@{
    ViewData["Title"] = "Nuevo Material";
}

<h1 class="my-4">Agregar Nuevo Material</h1>

<form method="post">
    <div class="form-group">
        <label for="IdNombreExistente">Elegir Nombre Existente:</label>
        @if (Model.EsNuevo)
        {
            <select class="form-control" id="IdNombreExistente" asp-for="datoMaterialAgregar.Id">
                <option value="-1">Escribir Nuevo Nombre</option>
                @foreach (var nombreExistente in Model.NombresExistentes)
                {
                    <option value="@nombreExistente.Id">@nombreExistente.Nombre</option>
                }
            </select>
        }
        else
        {
            <input type="text" class="form-control" id="NombreExistente" value="@Model.datoMaterialAgregar.Nombre" readonly />
            <input type="hidden" id="IdNombreExistente" asp-for="datoMaterialAgregar.Id" />
        }
    </div>
    @if (Model.EsNuevo)
    {
        <div class="form-group opcionNewName">
            <label for="Nombre">Nombre:</label>
            <input type="text" class="form-control" id="Nombre" asp-for="datoMaterialAgregar.Nombre" />
        </div>
    }else{
        <input type="hidden" id="Nombre" asp-for="datoMaterialAgregar.Nombre" />
    }
    <div class="form-group">
        <label for="NumeroInventario">Número de inventario:</label>
        @if (Model.EsNuevo){
            <input type="text" class="form-control" id="NumeroInventario" asp-for="materialAgregar.NumeroInventario"
            required />
        }else{
            <input type="text" class="form-control" id="NumeroInventario" asp-for="materialAgregar.NumeroInventario"
            required readonly/>
        }
        
    </div>
    <div class="form-group">
        <label for="Anio">Año:</label>
        <input type="number" class="form-control" id="Anio" asp-for="materialAgregar.AnioMaterial" required />
    </div>
    <div class="form-group">
        <label for="Estado">Estado:</label>
        <select class="form-control" id="Estado" asp-for="materialAgregar.Estado" required>
            <option value="Disponible">Disponible</option>
            <option value="En uso">En uso</option>
            <option value="En mantenimiento">En mantenimiento</option>
            <option value="No disponible">No disponible</option>
        </select>
    </div>
    @if (Model.EsNuevo)
    {
        <div class="form-group opcionNewName">
            <label for="Descripcion">Descripción:</label>
            <textarea class="form-control" id="Descripcion" asp-for="datoMaterialAgregar.Descripcion"></textarea>
        </div>
    }
    <p></p>
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        $('#IdNombreExistente').change(function () {
            if ($(this).val() == '-1') {
                $('.opcionNewName').show();
            } else {
                $('.opcionNewName').hide();
            }
        });
    });
</script>

Pages/Almacenista/OpcionesMateriales.cshtml
@page
@model ProyectoAlmacen.Pages.Almacenista.OpcionesMaterialesModel
@{
    ViewData["Title"] = "OpcionesMateriales";
}

<h1 class="my-4">Opciones de Materiales</h1>

<a class="btn btn-primary mb-3" asp-page="/Almacenista/AgregarMaterial">Agregar Nuevo Material</a>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Número de inventario</th>
            <th scope="col">Año</th>
            <th scope="col">Estado</th>
            <th scope="col">Descripción</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var material in Model.Materiales)
        {
            <tr>
                @if (material.DatosMaterialesNavigation != null)
                {
                    <td>@material.DatosMaterialesNavigation?.Nombre</td>
                    <td>@material.NumeroInventario</td>
                    <td>@material.AnioMaterial</td>
                    <td>@material.Estado</td>
                    <td>@material.DatosMaterialesNavigation?.Descripcion</td>
                    <td>
                        <form method="post" asp-page="/Almacenista/OpcionesMateriales" asp-page-handler="EditarMaterial">
                            <input type="hidden" name="materialId" value="@material.NumeroInventario" />
                            <button type="submit" class="btn btn-info btn-sm">Editar</button>
                        </form>
                        <form method="post" asp-page="/Almacenista/OpcionesMateriales" asp-page-handler="EliminarMaterial"
                        onsubmit="return confirm('¿Estás seguro de que quieres eliminar este material?');">
                            <input type="hidden" name="materialId" value="@material.NumeroInventario" />
                            <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                        </form>
                    </td>
                }
                else
                {
                    <h1>Error</h1>
                }

            </tr>
        }
    </tbody>
</table>

Pages/Almacenista/SolicitudesAlmacen.cshtml
@page
@model ProyectoAlmacen.Pages.Almacenista.SolicitudesAlmacenModel
@{
    ViewData["Title"] = "Listado de Solicitudes";
}
<h4>Ir a:</h4>
<a asp-page="/Almacenista/OpcionesMateriales" class="btn btn-primary">Opciones de materiales</a>

<div class="container">
    <!-- Pestañas de navegación -->
    <ul class="nav nav-tabs" id="myTabs">
        <li class="nav-item">
            <a class="nav-link active" id="solicitudesAprobadasTab" data-toggle="tab" href="#solicitudesAprobadas">Aprobadas</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="solicitudesAtrasadasTab" data-toggle="tab" href="#solicitudesAtrasadas">Atrasadas</a>
        </li>
        <li>
            <a class="nav-link" id="retornoPrestamosTab" data-toggle="tab" href="#retornoPrestamos">Retorno de Prestamos</a>
        </li>
        <!-- Agrega más pestañas según sea necesario -->
    </ul>

    <!-- Contenido de las pestañas -->
    <div class="tab-content">
        <!-- Sección de Solicitudes Aprobadas -->
        <div id="solicitudesAprobadas" class="tab-pane fade show active">
                    
            <h1>Listado de Solicitudes Aprobadas</h1>
            @if (Model.SolicitudesConMateriales != null && Model.SolicitudesConMateriales.Count > 0)
            {
                @foreach (var solicitud in Model.SolicitudesConMateriales)
                {
                    <div class="card mb-3">
                        <div class="card-header">
                            Solicitud de @solicitud.IdusuarioNavigation.NombreCompleto
                        </div>
                        <div class="card-body">
                            <p><strong>Salón:</strong> @solicitud.LaboratorioNavigation.NombreLaboratorio</p>
                            <p><strong>Fecha petición:</strong> @solicitud.FechaCreacion</p>
                            <p><strong>Fecha en la que se usará:</strong> @solicitud.FechaSolicitud</p>
                            <p><strong>Hora salida:</strong> @solicitud.HoraSolicitud</p>
                            <p><strong>Hora regreso:</strong> @solicitud.HoraRetorno</p>
                            <p><strong>Maestro:</strong> @solicitud.ProfesorNavigation.IdusuarioNavigation.NombreCompleto</p>
                            

                            <p><strong>Materiales Solicitados:</strong></p>
                            <ul>
                                @foreach (var material in solicitud.MaterialSolicituds)
                                {
                                    <li>@material.NumeroInventarioNavigation.DatosMaterialesNavigation.Nombre - 
                                        @material.NumeroInventarioNavigation.DatosMaterialesNavigation.Descripcion </li>
                                }
                            </ul>
                            <div class="text-center">
                                <form method="post">
                                    <button class="btn btn-primary" asp-page-handler="Prestar"
                                        asp-route-solicitudId="@solicitud.Id">Prestar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <p>No hay solicitudes aprobadas</p>
            }

        </div>

        <!-- Sección de Solicitudes Atrasadas -->
        <div id="solicitudesAtrasadas" class="tab-pane fade">
            <h1>Listado de Solicitudes Atrasadas</h1>
            @if (Model.SolicitudesAtrasadas != null && Model.SolicitudesAtrasadas.Count > 0)
            {
                @foreach (var solicitud in Model.SolicitudesAtrasadas)
                {
                    <div class="card mb-3">
                        <div class="card-header">
                            Solicitud de @solicitud.IdusuarioNavigation.NombreCompleto
                        </div>
                        <div class="card-body">
                            <p><strong>Salón:</strong> @solicitud.LaboratorioNavigation.NombreLaboratorio</p>
                            <p><strong>Fecha petición:</strong> @solicitud.FechaCreacion</p>
                            <p><strong>Fecha en la que se usará:</strong> @solicitud.FechaSolicitud</p>
                            <p><strong>Hora salida:</strong> @solicitud.HoraSolicitud</p>
                            <p><strong>Hora regreso:</strong> @solicitud.HoraRetorno</p>
                            <p><strong>Maestro:</strong> @solicitud.ProfesorNavigation.IdusuarioNavigation.NombreCompleto</p>
                            

                            <p><strong>Materiales Solicitados:</strong></p>
                            <ul>
                                @foreach (var material in solicitud.MaterialSolicituds)
                                {
                                    <li>@material.NumeroInventarioNavigation.DatosMaterialesNavigation.Nombre - 
                                        @material.NumeroInventarioNavigation.DatosMaterialesNavigation.Descripcion </li>
                                }
                            </ul>
                            <div class="text-center">
                                <form method="post">
                                    <button class="btn btn-primary" asp-page-handler="Prestar"
                                        asp-route-solicitudId="@solicitud.Id">Prestar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <p>No hay solicitudes atrasadas</p>
            }
        </div>

        <!-- Agrega más secciones según sea necesario -->
        
        <!-- Sección de Solicitudes Atrasadas -->
        <div id="retornoPrestamos" class="tab-pane fade">
            <h1>Listado de Prestamos Activos</h1>
            @if (Model.Prestamos != null && Model.Prestamos.Count > 0)
            {
                @foreach (var prestamo in Model.Prestamos)
                {
                    var solicitud = prestamo.IdsolicitudNavigation;
                    <div class="card mb-3">
                        <div class="card-header">
                            Solicitud de @solicitud.IdusuarioNavigation.NombreCompleto
                        </div>
                        <div class="card-body">
                            <p><strong>Salón:</strong> @solicitud.LaboratorioNavigation.NombreLaboratorio</p>
                            <p><strong>Fecha en la que se usará:</strong> @solicitud.FechaSolicitud</p>
                            <p><strong>Hora salida:</strong> @solicitud.HoraSolicitud</p>
                            <p><strong>Hora regreso:</strong> @solicitud.HoraRetorno</p>
                            <p><strong>Maestro:</strong> @solicitud.ProfesorNavigation.IdusuarioNavigation.NombreCompleto</p>
                            <p><strong>Estado:</strong> @prestamo.EstadoPrestamo</p>

                            <p><strong>Materiales Solicitados:</strong></p>
                            <ul>
                                @foreach (var material in solicitud.MaterialSolicituds)
                                {
                                    <li>@material.NumeroInventarioNavigation.DatosMaterialesNavigation.Nombre - 
                                        @material.NumeroInventarioNavigation.DatosMaterialesNavigation.Descripcion </li>
                                }
                            </ul>
                            <div class="text-center">
                                <form method="post">
                                    <button class="btn btn-primary" asp-page-handler="Prestar"
                                        asp-route-solicitudId="@solicitud.Id">Prestar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <p>No hay prestamos activos</p>
            }
        </div>
    </div>
</div>

<!-- Script para manejar las pestañas con animaciones -->
<script>
    $(document).ready(function () {
        // Configura el control de pestañas de Bootstrap
        $('#myTabs a').on('click', function (e) {
            e.preventDefault();
            $(this).tab('show');
        });
    });
</script>